### ISSUE TITLE
NPM run start error

### ISSUE THREAD

**Issue by lklsr** [flyve-mdm/flyve-mdm-web-ui#114]
Hi

When starting the service I'm having the problem attached, could they help me?

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! @teclib/flyve-mdm-web-ui@2.1.0 start: `npm i & bower i & grunt build & grunt serve`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the @teclib/flyve-mdm-web-ui@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lucas.ribeiro\AppData\Roaming\npm-cache\_logs\2018-01-07T19_32_41_874Z-debug.log

![image](https://user-images.githubusercontent.com/18348158/34653385-33530d6c-f3d2-11e7-941a-cb771c46899d.png)

**Comment by lklsr** [comment]
log is:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose config Skipping project config: C:\Users\lucas.ribeiro/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle @teclib/flyve-mdm-web-ui@2.1.0~prestart: @teclib/flyve-mdm-web-ui@2.1.0
7 info lifecycle @teclib/flyve-mdm-web-ui@2.1.0~start: @teclib/flyve-mdm-web-ui@2.1.0
8 verbose lifecycle @teclib/flyve-mdm-web-ui@2.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle @teclib/flyve-mdm-web-ui@2.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\lucas.ribeiro\node_modules\.bin;C:\oracle\product\10.2.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\PuTTY\;C:\Users\lucas.ribeiro\AppData\Local\Programs\Python\Python36\Scripts;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Ruby25-x64\bin;C:\Users\lucas.ribeiro\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\lucas.ribeiro\AppData\Local\Programs\Python\Python36\;C:\Users\lucas.ribeiro\AppData\Local\Microsoft\WindowsApps;C:\Users\lucas.ribeiro\AppData\Local\Programs\Python\Python36\Lib\site-packages\numpy;C:\Users\lucas.ribeiro\AppData\Roaming\npm
10 verbose lifecycle @teclib/flyve-mdm-web-ui@2.1.0~start: CWD: C:\Users\lucas.ribeiro
11 silly lifecycle @teclib/flyve-mdm-web-ui@2.1.0~start: Args: [ '/d /s /c', 'npm i & bower i & grunt build & grunt serve' ]
12 silly lifecycle @teclib/flyve-mdm-web-ui@2.1.0~start: Returned: code: 6  signal: null
13 info lifecycle @teclib/flyve-mdm-web-ui@2.1.0~start: Failed to exec start script
14 verbose stack Error: @teclib/flyve-mdm-web-ui@2.1.0 start: `npm i & bower i & grunt build & grunt serve`
14 verbose stack Exit status 6
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid @teclib/flyve-mdm-web-ui@2.1.0
16 verbose cwd C:\Users\lucas.ribeiro
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.9.4
20 verbose npm  v5.6.0
21 error code ELIFECYCLE
22 error errno 6
23 error @teclib/flyve-mdm-web-ui@2.1.0 start: `npm i & bower i & grunt build & grunt serve`
23 error Exit status 6
24 error Failed at the @teclib/flyve-mdm-web-ui@2.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 6, true ]
